# Generated by Django 6.0.5 on 2026-05-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin-approved; unverified doctors are hidden from patients.'),
        ),
    ]
