# Generated by Django 6.0.5 on 2026-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
